import type { ReactNode } from 'react';
import type { Analysis } from '../types';
import { coins, n } from '../fmt';
import { Chip, Lightbox, Panel, Section, Stat } from './ui';

/* PROVENANCE — the credibility of the entire project.
   A judge opens a finished report about a stranger's repository and has no
   reason to believe public/analysis.json was not hand-written. The answer is
   one chain, not three paragraphs: the same figure shown in Bob's own IDE
   panel, in the committed export, and read back out of analysis.json at
   runtime. 0.469 in Bob's badge is 0.468592 in the export and 0.468592 in the
   third column, where this page prints the file rather than retyping it. */

const SHOT_01 = 'bob_sessions/receipts_task01_lib_rename_summary.png';
const SHOT_02 = 'bob_sessions/receipts_task02_lib_jsdoc_summary.png';
const SOURCE = 'receipts_task01_lib_rename_export.json';
// blob/HEAD, not blob/main: a default-branch rename must not turn the one link
// that proves the claim into a 404.
const SOURCE_URL = `https://github.com/ishal1410/receipts/blob/HEAD/bob_sessions/${SOURCE}`;

// Transcribed from `tasks[0].task.costs` of the file above. Complete except the
// trailing `key` field, which is a cache identifier and measures nothing.
const COSTS = [
  '"costs": {',
  '  "cost": 0.468592,',
  '  "contextTokens": 50636,',
  '  "contextWindowBreakdown": {',
  '    "total": 29711,',
  '    "reportedTotal": 50636,',
  '    "breakdown": {',
  '      "roleDefinition": 34,',
  '      "staticSections": 563,',
  '      "skills": 18572,',
  '      "baseRules": 197,',
  '      "projectRules": 0,',
  '      "customInstructions": 188,',
  '      "environment": 72,',
  '      "toolSystemPrompts": 3340,',
  '      "toolDefinitions": 6745,',
  '      "mcpToolDefinitions": 0',
  '    },',
  '    "loadedSkills": []',
  '  }',
  '}',
];

// DRIFT GUARD. The block above is a static transcription; analysis.json is
// regenerated by `npm run snapshot`. If a re-snapshot ever stops agreeing, the
// closing sentence must stop asserting a match rather than assert a false one.
const EXPECTED = { coins: 0.468592, reported: 50636, skills: 18572 };

function tint(line: string): string | undefined {
  if (line.includes('"cost":')) return 'var(--color-spend)';
  if (line.includes('"contextTokens":') || line.includes('"skills":')) return 'var(--color-overhead)';
  if (line.includes('"loadedSkills"')) return 'var(--color-dead)';
  return undefined;
}

function Step({
  i, title, body, children,
}: { i: number; title: string; body: ReactNode; children: ReactNode }) {
  return (
    <div className="flex h-full flex-col p-5 sm:p-7">
      <div className="flex items-center gap-3">
        <span className="num grid size-7 shrink-0 place-items-center rounded-full border hair bg-white/4 text-[12px] text-fg-2">
          {i}
        </span>
        <h3 className="min-w-0">{title}</h3>
      </div>
      <p className="mt-3.5 text-[14px] leading-relaxed text-fg-2">{body}</p>
      <div className="mt-5 flex-1">{children}</div>
    </div>
  );
}

export default function Proof({ analysis }: { analysis: Analysis }) {
  // Matched on sourceFile, the field snapshot.mjs writes for exactly this
  // purpose. Rebuilt from a different corpus, column three drops its figures
  // instead of inventing them.
  const t = analysis.tasks.find((x) => x.sourceFile === SOURCE);
  const matches =
    !!t &&
    t.coins === EXPECTED.coins &&
    t.context.reportedTotal === EXPECTED.reported &&
    t.context.breakdown.skills === EXPECTED.skills;

  return (
    <Section
      id="proof"
      eyebrow="Provenance"
      tone="var(--color-spend)"
      title={<>0.469 in Bob&rsquo;s panel.<br className="hidden sm:block" /> 0.468592 everywhere else.</>}
      lede={
        <>
          Receipts invents nothing. Bob prices the task and itemises the window himself,
          then closes the session; this page is the same three artifacts put back on the
          table, in order, with the same figures visible in all three.
        </>
      }
      wide
    >
      <div className="grid gap-5 lg:grid-cols-12">
        <Panel className="lg:col-span-5">
          <Step
            i={1}
            title="Bob prices it"
            body={<>His panel shows a coin badge and a token counter while the task runs. Close it and that is the last anyone sees of either.</>}
          >
            <Lightbox
              src={`${import.meta.env.BASE_URL}${SHOT_01}`}
              width={1285}
              height={973}
              alt="The IBM Bob task panel for task 01 of this repository, showing a 0.469 coin badge, a 50.6k of 270.0k token counter, the prompt, and the tool calls Bob ran."
              caption={
                <>
                  Task 01 of this repository as Bob drew it:{' '}
                  <span className="num text-spend">0.469</span> coins,{' '}
                  <span className="num text-overhead">50.6k</span> of 270.0k tokens. The{' '}
                  <a className="underline decoration-white/25 underline-offset-2 transition-colors duration-300 hover:text-fg"
                     href={`${import.meta.env.BASE_URL}${SHOT_02}`}>second session</a>{' '}
                  is in the repo too.
                </>
              }
            />
          </Step>
        </Panel>

        <Panel className="lg:col-span-4">
          <Step
            i={2}
            title="Bob exports it"
            body={<>He writes the finished task to JSON. That export is the only input format Receipts accepts, and it is committed here.</>}
          >
            <a
              className="num block break-all text-[11.5px] text-muted underline decoration-white/20 underline-offset-2 transition-colors duration-300 hover:text-fg"
              href={SOURCE_URL}
              target="_blank"
              rel="noreferrer noopener"
            >
              bob_sessions/{SOURCE}
            </a>
            {/* overflow-x on the block, never on the document: at 390px the
                longest line is wider than the column and the column scrolls. */}
            <pre className="num mt-3 overflow-x-auto rounded-lg border hair bg-raised p-3.5 text-[11.5px] leading-[1.65]">
              {COSTS.map((line) => (
                <span key={line} className="block" style={{ color: tint(line) ?? 'var(--color-fg-2)' }}>
                  {line}
                </span>
              ))}
            </pre>
            <p className="mt-3 text-[13px] text-muted">
              <span className="num">task.costs</span>, complete but for its cache key.
            </p>
          </Step>
        </Panel>

        <Panel className="lg:col-span-3">
          <Step
            i={3}
            title="One command"
            body={<><span className="num">npm run snapshot</span> joins every export to git history and writes <span className="num">public/analysis.json</span>. This page is that file.</>}
          >
            {t ? (
              <div className="space-y-6">
                <Stat value={coins(t.coins)} label="bobcoins billed" tone="var(--color-spend)" />
                <Stat value={n(t.context.reportedTotal)} label="tokens Bob reported" tone="var(--color-overhead)" />
                <Stat value={n(t.context.breakdown.skills ?? 0)} label="of them skill definitions" tone="var(--color-overhead)" />
                <Stat value={`${t.survived}/${t.authored}`} label="lines still at HEAD" tone="var(--color-live)" />
                <div><Chip>read from analysis.json at runtime</Chip></div>
              </div>
            ) : (
              <p className="text-[13px] leading-relaxed text-muted">
                This snapshot was built from a different corpus, so the session above is not
                in it. The figures for the sessions it does contain are in the ledger below.
              </p>
            )}
          </Step>
        </Panel>
      </div>

      <p className="mt-5 max-w-4xl text-[14px] leading-relaxed text-muted">
        {matches
          ? <>Bob&rsquo;s panel rounds what the export spells out: <span className="num text-spend">0.469</span> and <span className="num text-overhead">50.6k</span> there, <span className="num text-spend">0.468592</span> and <span className="num text-overhead">50,636</span> in the JSON and again in column three, where this page reads them out of the file rather than retyping them. The export is committed in the repository, so the chain is checkable without trusting this page.</>
          : <>The export is committed in the repository, so the chain is checkable without trusting this page: open it, find <span className="num">task.costs</span>, compare it against the screenshot. The figures in column three come from the current snapshot, which no longer agrees with the transcribed block.</>}
      </p>
    </Section>
  );
}
