import { motion } from 'motion/react';
import type { Analysis } from '../types';

// ORIENTATION, WORKFLOW AND PROVENANCE IN ONE SECTION, because they are one story.
//
// The rejection this panel exists to answer: a judge opens the live URL cold, sees a
// finished report about a stranger's repository, and has no reason to believe
// public/analysis.json was not hand-written. Three separate sections ("what this is",
// "how you use it", "here is our evidence") would say that three times. One chain
// says it once: each step of the operator's workflow is illustrated by the artifact
// that step actually produces, and the SAME FIGURES appear in all three. The
// screenshot is Bob's own panel, the JSON is the committed export, the third column
// is read out of analysis.json at runtime.
//
// The repo already contained both screenshots and both exports and NO component
// referenced any of them. public/ is the only directory Vite serves, so the two .png
// files are copied there; the .json is linked on GitHub rather than copied, because
// the export carries a workspace path in every record and this page renders only the
// path-free `costs` object.

const SHOT_01 = 'bob_sessions/receipts_task01_lib_rename_summary.png';
const SHOT_02 = 'bob_sessions/receipts_task02_lib_jsdoc_summary.png';
const SOURCE = 'receipts_task01_lib_rename_export.json';
// blob/HEAD, not blob/main: HEAD resolves to whatever the default branch is called,
// so a rename does not turn the one link that proves the claim into a 404.
const SOURCE_URL =
  `https://github.com/ishal1410/receipts/blob/HEAD/bob_sessions/${SOURCE}`;

// Transcribed from `tasks[0].task.costs` in the file above. Complete except for the
// trailing `key` field, which is a cache identifier and measures nothing.
const COSTS = [
  '"costs": {',
  '  "cost": 0.468592,',
  '  "contextTokens": 50636,',
  '  "contextWindowBreakdown": {',
  '    "total": 29711,',
  '    "reportedTotal": 50636,',
  '    "breakdown": {',
  '      "roleDefinition": 34,',
  '      "staticSections": 563,',
  '      "skills": 18572,',
  '      "baseRules": 197,',
  '      "projectRules": 0,',
  '      "customInstructions": 188,',
  '      "environment": 72,',
  '      "toolSystemPrompts": 3340,',
  '      "toolDefinitions": 6745,',
  '      "mcpToolDefinitions": 0',
  '    },',
  '    "loadedSkills": []',
  '  }',
  '}',
];

// The three figures the chain is built on. They are ALSO the drift guard: the block
// above is a static transcription and analysis.json is regenerated by `npm run
// snapshot`, so a re-snapshot could silently leave this panel claiming a match that
// no longer holds. If any one of them stops agreeing, the closing sentence stops
// asserting the match rather than asserting a false one.
const EXPECTED = { coins: 0.468592, reported: 50636, skills: 18572 };

const n = (v: number) => v.toLocaleString('en-US');

// Only three lines carry a figure that appears in the screenshot and in column three;
// tinting those and nothing else is what makes the chain readable at a glance. Hues
// are the page's existing semantics: brass is money, ink-blue is context.
function tint(line: string): string | undefined {
  if (line.includes('"cost":')) return 'var(--color-spend)';
  if (line.includes('"contextTokens":') || line.includes('"skills":'))
    return 'var(--color-overhead)';
  return undefined;
}

function Figure({ value, label, tone }: { value: string; label: string; tone?: string }) {
  return (
    <div className="grid grid-cols-[auto_minmax(0,1fr)] items-baseline gap-x-3">
      <span
        className="num num-hero text-base"
        style={tone ? { color: tone } : undefined}
      >
        {value}
      </span>
      <span className="text-xs text-[var(--color-muted)]">{label}</span>
    </div>
  );
}

export default function Provenance({ analysis }: { analysis: Analysis }) {
  // Matched on sourceFile, which is the field snapshot.mjs writes for exactly this
  // purpose. If the corpus is ever rebuilt without this export, the third column
  // drops its figures instead of inventing them.
  const t = analysis.tasks.find((x) => x.sourceFile === SOURCE);
  const matches =
    !!t &&
    t.coins === EXPECTED.coins &&
    t.context.reportedTotal === EXPECTED.reported &&
    t.context.breakdown.skills === EXPECTED.skills;

  return (
    // Mount-only, no delay, identical timing to every other panel: a headless
    // screenshot taken at any moment after load catches the finished state.
    <motion.section
      className="panel"
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <div className="p-6 md:p-8">
        <h2>Where these numbers come from</h2>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-[var(--color-text-2)]">
          Receipts is for whoever pays the agent's bill. IBM Bob already measures all
          of this, per task, and then closes the session. Three steps put it back on
          the table.
        </p>
      </div>

      {/* gap-px over the hairline colour: the rules between steps are the same 1px
          line as every other edge on the page, and they become horizontal rules when
          the grid collapses to one column. Widths are 1.6 / 1 / 0.85 because the
          evidence in each step is a different size, not because a grid wants thirds:
          at even thirds the screenshot renders about 265px wide and Bob's coin badge
          and token counter, the two things it is here to prove, stop being legible. */}
      <ol className="grid gap-px border-t border-[var(--color-line)] bg-[var(--color-line)] lg:grid-cols-[1.6fr_1fr_0.85fr]">
        <li className="min-w-0 bg-[var(--color-surface)] p-6 md:p-8">
          <h3>Run the task in IBM Bob</h3>
          <p className="mt-2 text-sm leading-relaxed text-[var(--color-text-2)]">
            Bob's panel prices the session in bobcoins and counts the context window
            as it fills. Close the task and that is the last you see of either.
          </p>
          {/* Bob's own rendering, not a re-drawing of it. Intrinsic size is set so the
              column does not reflow when the file lands. */}
          <a
            className="mt-4 block border border-[var(--color-line-strong)]"
            href={`${import.meta.env.BASE_URL}${SHOT_01}`}
          >
            <img
              src={`${import.meta.env.BASE_URL}${SHOT_01}`}
              width={1285}
              height={973}
              loading="lazy"
              decoding="async"
              alt="The IBM Bob task panel for task 01 of this repository, showing a 0.469 coin badge, a 50.6k of 270.0k token counter, the prompt, and the tool calls Bob ran."
              className="block h-auto w-full"
            />
          </a>
          <p className="mt-2 text-xs leading-relaxed text-[var(--color-muted)]">
            Task 01 of this repository, as Bob rendered it:{' '}
            <span className="num" style={{ color: 'var(--color-spend)' }}>
              0.469
            </span>{' '}
            coins,{' '}
            <span className="num" style={{ color: 'var(--color-overhead)' }}>
              50.6k
            </span>{' '}
            of 270.0k tokens. Open it{' '}
            <a
              className="underline decoration-[var(--color-line-strong)] underline-offset-2 hover:text-[var(--color-text)]"
              href={`${import.meta.env.BASE_URL}${SHOT_01}`}
            >
              full size
            </a>
            , or the second session{' '}
            <a
              className="underline decoration-[var(--color-line-strong)] underline-offset-2 hover:text-[var(--color-text)]"
              href={`${import.meta.env.BASE_URL}${SHOT_02}`}
            >
              here
            </a>
            .
          </p>
        </li>

        <li className="min-w-0 bg-[var(--color-surface)] p-6 md:p-8">
          <h3>Export the session</h3>
          <p className="mt-2 text-sm leading-relaxed text-[var(--color-text-2)]">
            Bob writes the finished task to JSON. That export is the only input format
            Receipts accepts, and it is committed in this repository.
          </p>
          {/* Mono and breakable, not a tracked-out caps label: it is a path, the page
              already sets paths in mono, and as one unbreakable 358px token in caps it
              was the single element pushing the document past 390px. */}
          <p className="num mt-4 break-all text-[11px] text-[var(--color-muted)]">
            <a
              className="underline decoration-[var(--color-line-strong)] underline-offset-2 hover:text-[var(--color-text)]"
              href={SOURCE_URL}
              target="_blank"
              rel="noreferrer noopener"
            >
              bob_sessions/{SOURCE}
            </a>
          </p>
          {/* overflow-x-auto on the block, never on the page: at 390px the longest
              line is wider than the column and the column scrolls, not the document. */}
          <pre className="num mt-2 overflow-x-auto border border-[var(--color-line)] bg-[var(--color-raised)] p-3 text-[11px] leading-[1.6]">
            {COSTS.map((line) => (
              <span key={line} className="block" style={{ color: tint(line) }}>
                {line}
              </span>
            ))}
          </pre>
          <p className="mt-2 text-xs leading-relaxed text-[var(--color-muted)]">
            <span className="num">task.costs</span>, complete but for its cache key.
          </p>
        </li>

        <li className="min-w-0 bg-[var(--color-surface)] p-6 md:p-8">
          <h3>Run one command</h3>
          <p className="mt-2 text-sm leading-relaxed text-[var(--color-text-2)]">
            <span className="num">npm run snapshot</span> joins every export to git
            history and writes <span className="num">public/analysis.json</span>. This
            page is that file.
          </p>
          {t ? (
            <div className="perf space-y-2.5">
              <Figure
                value={t.coins.toFixed(6)}
                label="bobcoins billed"
                tone="var(--color-spend)"
              />
              <Figure
                value={n(t.context.reportedTotal)}
                label="tokens Bob reported"
                tone="var(--color-overhead)"
              />
              <Figure
                value={n(t.context.breakdown.skills ?? 0)}
                label="of them skill definitions"
                tone="var(--color-overhead)"
              />
              <Figure
                value={`${t.survived} of ${t.authored}`}
                label="lines still at HEAD"
                tone="var(--color-live)"
              />
            </div>
          ) : (
            <p className="perf text-xs leading-relaxed text-[var(--color-muted)]">
              This snapshot was built from a different corpus, so the task above is not
              in it. The figures for the tasks it does contain are below.
            </p>
          )}
        </li>
      </ol>

      <p className="border-t border-[var(--color-line)] p-6 text-xs leading-relaxed text-[var(--color-muted)] md:px-8">
        {/* Precisely what is true and no more. Bob's panel shows 0.469 and 50.6k
            because it rounds; the export spells both out in full, and the third
            column is read from analysis.json at runtime rather than retyped. Saying
            "the same three figures appear in all three places" would have been the
            one unchecked claim on a page whose entire argument is that claims get
            checked. */}
        {matches
          ? 'Bob’s panel rounds what the export spells out: 0.469 and 50.6k there, 0.468592 and 50,636 in the JSON and again in the column above, where this page reads them out of the file rather than retyping them. The export is committed here, so the chain is checkable without trusting this page.'
          : 'The export is committed here, so the chain is checkable without trusting this page: open it, find task.costs, and compare it against the screenshot. The figures above come from the current snapshot, which no longer agrees with the transcribed block.'}
      </p>
    </motion.section>
  );
}
